### ISSUE TITLE
cannot find -liconv when building on Ubuntu 12.04

### ISSUE THREAD

**Issue by ungsophy** [smparkes/zxing.rb#3]
Hi, I have problem when building zxing.rb on Ubuntu 12.04. It says `/usr/bin/ld: cannot find -liconv`, but luckily I got it working after installing `libiconv` from source. I think it might be useful to post it for others that might have the same problem. To install `libiconv` from source:

```
wget http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.13.1.tar.gz
tar xvfz libiconv-1.13.1.tar.gz
cd libiconv-1.13.1
./configure --prefix=/usr/local/Cellar/libiconv/1.13.1
make
sudo make install
```

Then restart the building process. Good luck!

**Comment by smparkes** [comment]
You don't actually need libiconv. The necessary functions are in libc, at least on ubuntu (though I'm not 100% sure how they're implemented ...)

What needed to be done was to not use -liconv on ubuntu (or other hosts that don't have /usr/lib/libiconv) while leaving it where needed, e.g., osx. Fixed in ffa1cc6e493c27b0b7713d9f3cc37399239dce97
